import "dotenv/config";
import postgres from "postgres";

const sql = postgres(process.env.DATABASE_URL);

const companies = ["Google", "Meta", "Apple", "Amazon", "Microsoft", "Netflix", "Spotify", "Airbnb", "Uber", "Stripe"];

const titles = [
  "Frontend Developer",
  "Backend Engineer",
  "Full Stack Developer",
  "Software Engineer",
  "DevOps Engineer",
  "Data Engineer",
  "Product Manager",
  "UI/UX Designer",
  "QA Engineer",
  "Cloud Architect",
];

const locations = [
  "London",
  "Manchester",
  "Birmingham",
  "Edinburgh",
  "Bristol",
  "Leeds",
  "Liverpool",
  "Glasgow",
  "Cardiff",
  "Remote",
];

const statuses = ["Applied", "Interview", "Offer", "Rejected"];

const employmentTypes = ["Full-time", "Part-time", "Contract", "Internship"];

function random(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function randomSalary() {
  const min = Math.floor(Math.random() * 40 + 30) * 1000; // 30k–70k
  const max = min + Math.floor(Math.random() * 30 + 5) * 1000;
  return `${min} - ${max} a year`;
}

const applications = Array.from({ length: 300 }, (_, i) => ({
  url: `https://linkedin.com/jobs/${i + 1}`,
  title: random(titles),
  company: random(companies),
  location: random(locations),
  description: `This is a sample job description for job ${i + 1}.`,
  status: random(statuses),
  salary: randomSalary(),
  employment_type: random(employmentTypes),
}));

for (const app of applications) {
  await sql`
    INSERT INTO applications (
      url,
      title,
      company,
      location,
      description,
      status,
      salary,
      employment_type
    )
    VALUES (
      ${app.url},
      ${app.title},
      ${app.company},
      ${app.location},
      ${app.description},
      ${app.status},
      ${app.salary},
      ${app.employment_type}
    )
    ON CONFLICT (url) DO NOTHING
  `;
}

await sql.end();
console.log("Seeded 300 applications");

// This javascript code is generated by AI, it is used for development purposes only. -Tian
