import "dotenv/config";
import postgres from "postgres";

const sql = postgres(process.env.DATABASE_URL);

const companies = ["Google", "Meta", "Apple", "Amazon", "Microsoft", "Netflix", "Spotify", "Airbnb", "Uber", "Stripe"];
const titles = [
  "Frontend Developer",
  "Backend Engineer",
  "Full Stack Developer",
  "Software Engineer",
  "DevOps Engineer",
  "Data Engineer",
  "Product Manager",
  "UI/UX Designer",
  "QA Engineer",
  "Cloud Architect",
];
const locations = [
  "London",
  "Manchester",
  "Birmingham",
  "Edinburgh",
  "Bristol",
  "Leeds",
  "Liverpool",
  "Glasgow",
  "Cardiff",
  "Remote",
];
const statuses = ["applied", "interview", "offer", "rejected"];

function random(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

const applications = Array.from({ length: 300 }, (_, i) => ({
  url: `https://linkedin.com/jobs/${i + 1}`,
  title: random(titles),
  company: random(companies),
  location: random(locations),
  description: `This is a sample job description for job ${i + 1}.`,
  status: random(statuses),
}));

for (const app of applications) {
  await sql`
    INSERT INTO applications (url, title, company, location, description, status)
    VALUES (${app.url}, ${app.title}, ${app.company}, ${app.location}, ${app.description}, ${app.status})
    ON CONFLICT (url) DO NOTHING
  `;
}

await sql.end();
console.log("Seeded 300 applications");

// This javascript code is generated by AI, it is used for development purposes only. -Tian
